### ISSUE TITLE
Specifying default parameters malforms values if they exist

### ISSUE THREAD

**Issue by sagebind** [oh-my-fish/plugin-config#2]
When using `--default`, if fetching the value of a config property is successful, the default value is appended to the real value:

``` fish
$ config foo --get property --default default
default
$ config foo --set property value
$ config foo --get property --default default
valuedefault
```

**Comment by therealpxc** [comment]
I haven't been able to do anything with `--default`. Is it only used with `--get` as a shortcut for some error handling?

**Comment by sagebind** [comment]
@therealpxc Yes; it is used internally by the `tmux-zen` package to supply a default binary if none is specified.

**Comment by therealpxc** [comment]
Thanks again, Stephen!
